### ISSUE TITLE
[Bug] 0.2.0 Build failing to open

### ISSUE THREAD

**Issue by bryce-seifert** [Julusian/companion-remote#12]
<img width="255" alt="Screen Shot 2021-01-20 at 7 49 32 PM" src="https://user-images.githubusercontent.com/50299051/105268939-ad704d80-5b58-11eb-9b58-42b5ce277cce.png">

**Comment by Julusian** [comment]
I overlooked testing the builds as it worked fine on linux...
Ill try and get a fix together today, but 0.1.0 works well enough until then

**Comment by Julusian** [comment]
https://github.com/Julusian/companion-remote/releases/tag/v0.2.1

This time I tested it on both mac and windows ;)
