### ISSUE TITLE
[Bug] Windows 10, javascript error

### ISSUE THREAD

**Issue by kraves-oz** [Julusian/companion-remote#13]
Thought I'd pass on an error I'm getting today after a first time install.

See screenshot.  When opens get this popup, then after clearing popup task manager shows 3 Companion Remote processes.
Current windows 10 Home 20H2 install with latest updates if it helps.

Thanks, otherwise looks like a handy little project.

![Capture error](https://user-images.githubusercontent.com/42990369/105274530-1901fb80-5be9-11eb-903e-9e0d48438e01.JPG)

**Comment by Julusian** [comment]
Duplicate of #12 

I overlooked testing the builds as it worked fine on linux...
Ill try and get a fix together today, but 0.1.0 works well enough until then

**Comment by Julusian** [comment]
Fixed in https://github.com/Julusian/companion-remote/releases/tag/v0.2.1
