### ISSUE TITLE
fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648

### ISSUE THREAD

**Issue by alatteri** [Julusian/companion-remote#20]
Got things working, but the screen is corrupted and this error is output.

```
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
device(BL31J1B01102): fillImage failed: RangeError: Expected image buffer of length 19200, got length 27648
```

![IMG_1138](https://user-images.githubusercontent.com/625982/110364668-e6755c00-7ff8-11eb-8b16-ac6d8a27ae2d.jpeg)

**Comment by Julusian** [comment]
The text error there is going to be because it couldn't find the 'sans-serif' font for the drawing. I don't know why that would be.

for the fillImage error, I have pushed a fix. Do a `git pull` and `yarn build` and try running it again

**Comment by alatteri** [comment]
Fixed.  Thanks!!!!  Really appreciate your help, and doing this project.
