### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by alatteri** [Julusian/companion-remote#21]
Hi,  I'd like to make a $ donation to this project/author.  Being able to use Satellite decks as opposed to having to run local Companion on each device is amazing.

**Comment by JeffreyDavidsz** [comment]
If there isn't any link for donating, you could donate it to Bitfocus and I'll make sure @Julusian will receive it (send a message when you did it)

**Comment by alatteri** [comment]
Just now.

**Comment by JeffreyDavidsz** [comment]
@alatteri I've messaged you on slack about this, to verify it was you, could you check?

**Comment by alatteri** [comment]
> @alatteri I've messaged you on slack about this, to verify it was you, could you check?

Hi Jeff.... I haven't been on slack in awhile. I don't even remember my credentials... I just created a new account under alan@ins*****.la

I made two donations on March 25th.   One larger, one smaller.  The larger was to the overall Companion project, and the smaller to the Satellite project.

Thanks.

**Comment by Julusian** [comment]
Thanks, I appreciate it :)
