### ISSUE TITLE
Lockout pin pad not shown

### ISSUE THREAD

**Issue by Toshiba01** [Julusian/companion-remote#23]
I'm trying the Companion-remote on the RPi 4 and everything runs fine. I activated the lockout function in Companion but unfortunately, It seems that it's not sending back the actual pin pad characters. If I press the buttons they are working and I can input the pin, but I can't see what I'm pressing. 
If I connect streamdeck directly to companion it works. 

Any thoughts? Maybe even a hint where I can modify the code to allow it happen. Thank you! 

Companion version: 2.2.0
Companion remote: (latest) 
RPI 4: 8GB model
Node version 14.16.0
Streamdeck: XL (32 buttons)

**Comment by Julusian** [comment]
I've just given this a try myself, and it is causing companion to get stuck in a crash loop. I had to manually disable the lockout feature in the db to let companion startup properly.
I think I can see the broken logic in the api causing the crash, so I shall try and do a fix for 2.2 

```
Apr 08 12:08:56 companion node[19879]: buffer.js:361
Apr 08 12:08:56 companion node[19879]:     throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
Apr 08 12:08:56 companion node[19879]:     ^
Apr 08 12:08:56 companion node[19879]: RangeError [ERR_INVALID_OPT_VALUE]: The value "NaN" is invalid for option "size"
Apr 08 12:08:56 companion node[19879]:     at Function.alloc (buffer.js:370:3)
Apr 08 12:08:56 companion node[19879]:     at new Buffer (buffer.js:284:19)
Apr 08 12:08:56 companion node[19879]:     at Serializer.serialize (/home/julus/companion-src/node_modules/binopsy/lib/serializer.js:40:11)
Apr 08 12:08:56 companion node[19879]:     at Bin.serialize (/home/julus/companion-src/node_modules/binopsy/index.js:34:26)
Apr 08 12:08:56 companion node[19879]:     at satellite.clearKey (/home/julus/companion-src/lib/satellite_device.js:187:43)
Apr 08 12:08:56 companion node[19879]:     at satellite.clearDeck (/home/julus/companion-src/lib/satellite_device.js:112:8)
Apr 08 12:08:56 companion node[19879]:     at device.drawPage (/home/julus/companion-src/lib/device.js:343:14)
Apr 08 12:08:56 companion node[19879]:     at EventEmitter.self.on_elgato_ready (/home/julus/companion-src/lib/device.js:99:9)
Apr 08 12:08:56 companion node[19879]:     at EventEmitter.emit (events.js:326:22)
Apr 08 12:08:56 companion node[19879]:     at EventEmitter.<anonymous> (/home/julus/companion-src/lib/satellite_device.js:52:10) {
Apr 08 12:08:56 companion node[19879]:   code: 'ERR_INVALID_OPT_VALUE'
Apr 08 12:08:56 companion node[19879]: }
```

**Comment by Toshiba01** [comment]
Interesting found! Is it actually fatal crashing your Companion? As on my machine it still runs, but just doesn't show up the "numbers". I'll have a closer look to some debug. Thanks for that!

**Comment by Julusian** [comment]
This is fixed in build 3455 of companion
