### ISSUE TITLE
Not able to build on arch arm (eg Raspberry Pi)

### ISSUE THREAD

**Issue by krisdahl** [Julusian/companion-remote#25]
I'm having difficulty getting it built on a Raspberry Pi / Arm.

> pi@raspberrypi:~/companion-remote $ yarn install
> yarn install v1.22.10
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> [4/5] Linking dependencies...
> warning " > @sofie-automation/code-standard-preset@0.2.2" has incorrect peer dependency "typescript@~4.0".
> [5/5] Building fresh packages...
> [1/8] ⠁ @julusian/jpeg-turbo
> [7/8] ⠁ electron
> [3/8] ⠁ sharp
> [4/8] ⠁ usb-detection
> error /home/pi/companion-remote/node_modules/@julusian/jpeg-turbo: Command failed.
> Exit code: 1
> Command: prebuild-install -r napi || cmake-js compile --target jpegturbo
> Arguments: 
> Directory: /home/pi/companion-remote/node_modules/@julusian/jpeg-turbo
> Output:
> prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm libc= platform=linux)
> [
>   '/usr/local/bin/node',
>   '/home/pi/companion-remote/node_modules/@julusian/jpeg-turbo/node_modules/.bin/cmake-js',
>   'compile',
>   '--target',
>   'jpegturbo'
> ]
> info TOOL Using Unix Makefiles generator.

**Comment by Julusian** [comment]
Try doing an `apt-get update && apt-get install -y cmake yasm` then try the `yarn install` again

**Comment by krisdahl** [comment]
Awesome that did work.  I didn't realize it was cmake that was missing.

I also had to install libudev and libusb packages.
