### ISSUE TITLE
Unable to read USB devices unless sudo/root permissions

### ISSUE THREAD

**Issue by krisdahl** [Julusian/companion-remote#26]
I'm running headless on a pi, and am able to get everything working if I run

`sudo node /home/pi/companion-remote/dist/main.js 10.1.1.2`

If I run without sudo (or use systems unit) I error opening up the USB devices.   Anyone know how to resolve?

> Connecting to 10.1.1.2:37133
> May 13 21:54:40 raspberrypi node[7752]: Connected
> May 13 21:54:40 raspberrypi node[7752]: sending version
> May 13 21:54:40 raspberrypi node[7752]: connected
> May 13 21:54:40 raspberrypi node[7752]: clear id map
> May 13 21:54:40 raspberrypi node[7752]: adding new device: 0001:0005:00
> May 13 21:54:40 raspberrypi node[7752]: existing = []
> May 13 21:54:40 raspberrypi node[7752]: Open "0001:0005:00" failed: TypeError: cannot open device with path 0001:0005:00
> May 13 21:54:40 raspberrypi node[7752]: Confirmed version PlainConstructor { versionMajor: 1, versionMinior: 1 }

**Comment by Julusian** [comment]
You probably need to follow the steps listed at https://github.com/julusian/node-elgato-stream-deck#linux to grant non-root users permission to access streamdecks.

I should add something to the readme here for this

**Comment by krisdahl** [comment]
Ahh perfect.  Yeah that is exactly what I needed, and I had looked at your node-elgato-stream-deck package but didn't see that note.

Wouldn't be terrible to actually to output on console when that error occurs to update the udevadm config.

Thanks for your help on this.
