### ISSUE TITLE
Bug: Closing About Windows causes Tray Icon to disappear (MacOS)

### ISSUE THREAD

**Issue by josephdadams** [Julusian/companion-remote#7]
Open the app
Click "About" in the tray
Close out the window
The app will disappear from the tray and generally went to "not responding" in activity monitor.

**Comment by josephdadams** [comment]
Sorry - this is basically #6

**Comment by Julusian** [comment]
https://github.com/Julusian/companion-remote/releases/tag/v0.2.0

I havent verified it on mac, but I could reproduce on linux and fixed it
